on:
  push:
    branches:
      - main
  workflow_dispatch:

# build:
#   ...
#   - run: dotnet build CosmicStoreAPI/CosmicStoreAPI.csproj -c Release
#   - run: dotnet publish CosmicStoreAPI/CosmicStoreAPI.csproj -c Release -o "${{ github.workspace }}/artifacts/api"
#   - upload path: ${{ github.workspace }}/artifacts/api

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cosmicstoreapi'
          slot-name: 'Production'
          package: .
